// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skins} from '../models';
import {main} from '../models';


export function ClearLisSkinsToken():Promise<void>;

export function HasLisSkinsToken():Promise<skins.LisSkinsTokenStatusResponse>;
export function DeleteSavedSkin(arg1:skins.DeleteSavedSkinRequest):Promise<void>;

export function GetSavedSkins(arg1:skins.GetSavedSkinsFilter):Promise<skins.SavedSkinsResponse>;

export function LogClientEvent(arg1:main.ClientLogEvent):Promise<void>;

export function SaveSkin(arg1:skins.SaveSkinRequest):Promise<skins.SaveSkinResponse>;

export function SetLisSkinsToken(arg1:skins.SetLisSkinsTokenRequest):Promise<void>;

export function SearchNewSkins(arg1:skins.SearchNewSkinsFilter):Promise<skins.NewSkinsResponse>;

export function Shutdown():Promise<void>;

export function UpdateAllSavedSkinsPrices(arg1:skins.UpdateAllSavedSkinsPricesRequest):Promise<skins.UpdateAllSavedSkinsPricesResponse>;

export function UpdateSavedSkinPrice(arg1:skins.UpdateSavedSkinPriceRequest):Promise<skins.UpdateSavedSkinPriceResponse>;
