// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSavedSkins(arg1) {
  return window['go']['main']['App']['GetSavedSkins'](arg1);
}

export function SearchNewSkins(arg1) {
  return window['go']['main']['App']['SearchNewSkins'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function UpdateAllSavedSkinsPrices(arg1) {
  return window['go']['main']['App']['UpdateAllSavedSkinsPrices'](arg1);
}

export function UpdateSavedSkinPrice(arg1) {
  return window['go']['main']['App']['UpdateSavedSkinPrice'](arg1);
}
