// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchNewSkins(arg1) {
  return window['go']['main']['App']['SearchNewSkins'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
