// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skins} from '../models';

export function GetSavedSkins(arg1:skins.GetSavedSkinsFilter):Promise<skins.SavedSkinsResponse>;

export function SaveSkin(arg1:skins.SaveSkinRequest):Promise<void>;

export function SearchNewSkins(arg1:skins.SearchNewSkinsFilter):Promise<skins.NewSkinsResponse>;

export function Shutdown():Promise<void>;

export function UpdateAllSavedSkinsPrices(arg1:skins.UpdateAllSavedSkinsPricesRequest):Promise<void>;

export function UpdateSavedSkinPrice(arg1:skins.UpdateSavedSkinPriceRequest):Promise<void>;
