// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLisSkinsToken() {
  return window['go']['main']['App']['ClearLisSkinsToken']();
}

export function DeleteSavedSkin(arg1) {
  return window['go']['main']['App']['DeleteSavedSkin'](arg1);
}

export function GetSavedSkins(arg1) {
  return window['go']['main']['App']['GetSavedSkins'](arg1);
}

export function HasLisSkinsToken() {
  return window['go']['main']['App']['HasLisSkinsToken']();
}

export function LogClientEvent(arg1) {
  return window['go']['main']['App']['LogClientEvent'](arg1);
}

export function SaveSkin(arg1) {
  return window['go']['main']['App']['SaveSkin'](arg1);
}

export function SearchNewSkins(arg1) {
  return window['go']['main']['App']['SearchNewSkins'](arg1);
}

export function SetLisSkinsToken(arg1) {
  return window['go']['main']['App']['SetLisSkinsToken'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function UpdateAllSavedSkinsPrices(arg1) {
  return window['go']['main']['App']['UpdateAllSavedSkinsPrices'](arg1);
}

export function UpdateSavedSkinPrice(arg1) {
  return window['go']['main']['App']['UpdateSavedSkinPrice'](arg1);
}
