// Code generated by ent, DO NOT EDIT.

package sourcestate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sourcestate type in the database.
	Label = "source_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldAPITokenEncrypted holds the string denoting the api_token_encrypted field in the database.
	FieldAPITokenEncrypted = "api_token_encrypted"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastErrorAt holds the string denoting the last_error_at field in the database.
	FieldLastErrorAt = "last_error_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the sourcestate in the database.
	Table = "source_states"
)

// Columns holds all SQL columns for sourcestate fields.
var Columns = []string{
	FieldID,
	FieldSource,
	FieldAPITokenEncrypted,
	FieldStatus,
	FieldLastSuccessAt,
	FieldLastError,
	FieldLastErrorAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultAPITokenEncrypted holds the default value on creation for the "api_token_encrypted" field.
	DefaultAPITokenEncrypted string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SourceState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByAPITokenEncrypted orders the results by the api_token_encrypted field.
func ByAPITokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPITokenEncrypted, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastErrorAt orders the results by the last_error_at field.
func ByLastErrorAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
