// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SkinsColumns holds the columns for the "skins" table.
	SkinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SkinsTable holds the schema information for the "skins" table.
	SkinsTable = &schema.Table{
		Name:       "skins",
		Columns:    SkinsColumns,
		PrimaryKey: []*schema.Column{SkinsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SkinsTable,
	}
)

func init() {
}
