// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppSettingsColumns holds the columns for the "app_settings" table.
	AppSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// AppSettingsTable holds the schema information for the "app_settings" table.
	AppSettingsTable = &schema.Table{
		Name:       "app_settings",
		Columns:    AppSettingsColumns,
		PrimaryKey: []*schema.Column{AppSettingsColumns[0]},
	}
	// PriceSnapshotsColumns holds the columns for the "price_snapshots" table.
	PriceSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// PriceSnapshotsTable holds the schema information for the "price_snapshots" table.
	PriceSnapshotsTable = &schema.Table{
		Name:       "price_snapshots",
		Columns:    PriceSnapshotsColumns,
		PrimaryKey: []*schema.Column{PriceSnapshotsColumns[0]},
	}
	// SkinsColumns holds the columns for the "skins" table.
	SkinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "market_hash_name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "name_color", Type: field.TypeString, Default: ""},
		{Name: "icon_url", Type: field.TypeString, Default: ""},
		{Name: "page_url", Type: field.TypeString, Default: ""},
		{Name: "price_text", Type: field.TypeString, Default: ""},
		{Name: "steam_page_url", Type: field.TypeString, Default: ""},
		{Name: "steam_price_text", Type: field.TypeString, Default: ""},
		{Name: "steam_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "lisskins_page_url", Type: field.TypeString, Default: ""},
		{Name: "lisskins_price_text", Type: field.TypeString, Default: ""},
		{Name: "lisskins_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "cstm_page_url", Type: field.TypeString, Default: ""},
		{Name: "cstm_price_text", Type: field.TypeString, Default: ""},
		{Name: "cstm_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "currency", Type: field.TypeString, Default: "1"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// SkinsTable holds the schema information for the "skins" table.
	SkinsTable = &schema.Table{
		Name:       "skins",
		Columns:    SkinsColumns,
		PrimaryKey: []*schema.Column{SkinsColumns[0]},
	}
	// SourceStatesColumns holds the columns for the "source_states" table.
	SourceStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source", Type: field.TypeString, Default: "lisskins"},
		{Name: "api_token_encrypted", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// SourceStatesTable holds the schema information for the "source_states" table.
	SourceStatesTable = &schema.Table{
		Name:       "source_states",
		Columns:    SourceStatesColumns,
		PrimaryKey: []*schema.Column{SourceStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sourcestate_source",
				Unique:  true,
				Columns: []*schema.Column{SourceStatesColumns[1]},
			},
		},
	}
	// WatchlistItemsColumns holds the columns for the "watchlist_items" table.
	WatchlistItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WatchlistItemsTable holds the schema information for the "watchlist_items" table.
	WatchlistItemsTable = &schema.Table{
		Name:       "watchlist_items",
		Columns:    WatchlistItemsColumns,
		PrimaryKey: []*schema.Column{WatchlistItemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppSettingsTable,
		PriceSnapshotsTable,
		SkinsTable,
		SourceStatesTable,
		WatchlistItemsTable,
	}
)

func init() {
}
