// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/predicate"
	"SkinPrice/skinprice/internal/adapters/database/ent/pricesnapshot"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceSnapshotUpdate is the builder for updating PriceSnapshot entities.
type PriceSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *PriceSnapshotMutation
}

// Where appends a list predicates to the PriceSnapshotUpdate builder.
func (_u *PriceSnapshotUpdate) Where(ps ...predicate.PriceSnapshot) *PriceSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMarketHashName sets the "market_hash_name" field.
func (_u *PriceSnapshotUpdate) SetMarketHashName(v string) *PriceSnapshotUpdate {
	_u.mutation.SetMarketHashName(v)
	return _u
}

// SetNillableMarketHashName sets the "market_hash_name" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillableMarketHashName(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetMarketHashName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *PriceSnapshotUpdate) SetSource(v string) *PriceSnapshotUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillableSource(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceLabel sets the "source_label" field.
func (_u *PriceSnapshotUpdate) SetSourceLabel(v string) *PriceSnapshotUpdate {
	_u.mutation.SetSourceLabel(v)
	return _u
}

// SetNillableSourceLabel sets the "source_label" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillableSourceLabel(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetSourceLabel(*v)
	}
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *PriceSnapshotUpdate) SetPageURL(v string) *PriceSnapshotUpdate {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillablePageURL(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// SetPriceText sets the "price_text" field.
func (_u *PriceSnapshotUpdate) SetPriceText(v string) *PriceSnapshotUpdate {
	_u.mutation.SetPriceText(v)
	return _u
}

// SetNillablePriceText sets the "price_text" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillablePriceText(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetPriceText(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *PriceSnapshotUpdate) SetPriceCents(v int64) *PriceSnapshotUpdate {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillablePriceCents(v *int64) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *PriceSnapshotUpdate) AddPriceCents(v int64) *PriceSnapshotUpdate {
	_u.mutation.AddPriceCents(v)
	return _u
}

// ClearPriceCents clears the value of the "price_cents" field.
func (_u *PriceSnapshotUpdate) ClearPriceCents() *PriceSnapshotUpdate {
	_u.mutation.ClearPriceCents()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PriceSnapshotUpdate) SetCurrency(v string) *PriceSnapshotUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillableCurrency(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *PriceSnapshotUpdate) SetFetchedAt(v time.Time) *PriceSnapshotUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillableFetchedAt(v *time.Time) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PriceSnapshotUpdate) SetMetadata(v string) *PriceSnapshotUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *PriceSnapshotUpdate) SetNillableMetadata(v *string) *PriceSnapshotUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// Mutation returns the PriceSnapshotMutation object of the builder.
func (_u *PriceSnapshotUpdate) Mutation() *PriceSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PriceSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PriceSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceSnapshotUpdate) check() error {
	if v, ok := _u.mutation.MarketHashName(); ok {
		if err := pricesnapshot.MarketHashNameValidator(v); err != nil {
			return &ValidationError{Name: "market_hash_name", err: fmt.Errorf(`ent: validator failed for field "PriceSnapshot.market_hash_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := pricesnapshot.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PriceSnapshot.source": %w`, err)}
		}
	}
	return nil
}

func (_u *PriceSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricesnapshot.Table, pricesnapshot.Columns, sqlgraph.NewFieldSpec(pricesnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MarketHashName(); ok {
		_spec.SetField(pricesnapshot.FieldMarketHashName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(pricesnapshot.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceLabel(); ok {
		_spec.SetField(pricesnapshot.FieldSourceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(pricesnapshot.FieldPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceText(); ok {
		_spec.SetField(pricesnapshot.FieldPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(pricesnapshot.FieldPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(pricesnapshot.FieldPriceCents, field.TypeInt64, value)
	}
	if _u.mutation.PriceCentsCleared() {
		_spec.ClearField(pricesnapshot.FieldPriceCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(pricesnapshot.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(pricesnapshot.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(pricesnapshot.FieldMetadata, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PriceSnapshotUpdateOne is the builder for updating a single PriceSnapshot entity.
type PriceSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PriceSnapshotMutation
}

// SetMarketHashName sets the "market_hash_name" field.
func (_u *PriceSnapshotUpdateOne) SetMarketHashName(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetMarketHashName(v)
	return _u
}

// SetNillableMarketHashName sets the "market_hash_name" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillableMarketHashName(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetMarketHashName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *PriceSnapshotUpdateOne) SetSource(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillableSource(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceLabel sets the "source_label" field.
func (_u *PriceSnapshotUpdateOne) SetSourceLabel(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetSourceLabel(v)
	return _u
}

// SetNillableSourceLabel sets the "source_label" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillableSourceLabel(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetSourceLabel(*v)
	}
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *PriceSnapshotUpdateOne) SetPageURL(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillablePageURL(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// SetPriceText sets the "price_text" field.
func (_u *PriceSnapshotUpdateOne) SetPriceText(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetPriceText(v)
	return _u
}

// SetNillablePriceText sets the "price_text" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillablePriceText(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetPriceText(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *PriceSnapshotUpdateOne) SetPriceCents(v int64) *PriceSnapshotUpdateOne {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillablePriceCents(v *int64) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *PriceSnapshotUpdateOne) AddPriceCents(v int64) *PriceSnapshotUpdateOne {
	_u.mutation.AddPriceCents(v)
	return _u
}

// ClearPriceCents clears the value of the "price_cents" field.
func (_u *PriceSnapshotUpdateOne) ClearPriceCents() *PriceSnapshotUpdateOne {
	_u.mutation.ClearPriceCents()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PriceSnapshotUpdateOne) SetCurrency(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillableCurrency(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *PriceSnapshotUpdateOne) SetFetchedAt(v time.Time) *PriceSnapshotUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillableFetchedAt(v *time.Time) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PriceSnapshotUpdateOne) SetMetadata(v string) *PriceSnapshotUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *PriceSnapshotUpdateOne) SetNillableMetadata(v *string) *PriceSnapshotUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// Mutation returns the PriceSnapshotMutation object of the builder.
func (_u *PriceSnapshotUpdateOne) Mutation() *PriceSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the PriceSnapshotUpdate builder.
func (_u *PriceSnapshotUpdateOne) Where(ps ...predicate.PriceSnapshot) *PriceSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PriceSnapshotUpdateOne) Select(field string, fields ...string) *PriceSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PriceSnapshot entity.
func (_u *PriceSnapshotUpdateOne) Save(ctx context.Context) (*PriceSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceSnapshotUpdateOne) SaveX(ctx context.Context) *PriceSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PriceSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.MarketHashName(); ok {
		if err := pricesnapshot.MarketHashNameValidator(v); err != nil {
			return &ValidationError{Name: "market_hash_name", err: fmt.Errorf(`ent: validator failed for field "PriceSnapshot.market_hash_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := pricesnapshot.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PriceSnapshot.source": %w`, err)}
		}
	}
	return nil
}

func (_u *PriceSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *PriceSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricesnapshot.Table, pricesnapshot.Columns, sqlgraph.NewFieldSpec(pricesnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PriceSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricesnapshot.FieldID)
		for _, f := range fields {
			if !pricesnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricesnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MarketHashName(); ok {
		_spec.SetField(pricesnapshot.FieldMarketHashName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(pricesnapshot.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceLabel(); ok {
		_spec.SetField(pricesnapshot.FieldSourceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(pricesnapshot.FieldPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceText(); ok {
		_spec.SetField(pricesnapshot.FieldPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(pricesnapshot.FieldPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(pricesnapshot.FieldPriceCents, field.TypeInt64, value)
	}
	if _u.mutation.PriceCentsCleared() {
		_spec.ClearField(pricesnapshot.FieldPriceCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(pricesnapshot.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(pricesnapshot.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(pricesnapshot.FieldMetadata, field.TypeString, value)
	}
	_node = &PriceSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
