// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/predicate"
	"SkinPrice/skinprice/internal/adapters/database/ent/pricesnapshot"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceSnapshotDelete is the builder for deleting a PriceSnapshot entity.
type PriceSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *PriceSnapshotMutation
}

// Where appends a list predicates to the PriceSnapshotDelete builder.
func (_d *PriceSnapshotDelete) Where(ps ...predicate.PriceSnapshot) *PriceSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PriceSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PriceSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PriceSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pricesnapshot.Table, sqlgraph.NewFieldSpec(pricesnapshot.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PriceSnapshotDeleteOne is the builder for deleting a single PriceSnapshot entity.
type PriceSnapshotDeleteOne struct {
	_d *PriceSnapshotDelete
}

// Where appends a list predicates to the PriceSnapshotDelete builder.
func (_d *PriceSnapshotDeleteOne) Where(ps ...predicate.PriceSnapshot) *PriceSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PriceSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pricesnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PriceSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
