// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/pricesnapshot"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PriceSnapshot is the model entity for the PriceSnapshot schema.
type PriceSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MarketHashName holds the value of the "market_hash_name" field.
	MarketHashName string `json:"market_hash_name,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceLabel holds the value of the "source_label" field.
	SourceLabel string `json:"source_label,omitempty"`
	// PageURL holds the value of the "page_url" field.
	PageURL string `json:"page_url,omitempty"`
	// PriceText holds the value of the "price_text" field.
	PriceText string `json:"price_text,omitempty"`
	// PriceCents holds the value of the "price_cents" field.
	PriceCents *int64 `json:"price_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// FetchedAt holds the value of the "fetched_at" field.
	FetchedAt time.Time `json:"fetched_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata     string `json:"metadata,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PriceSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricesnapshot.FieldID, pricesnapshot.FieldPriceCents:
			values[i] = new(sql.NullInt64)
		case pricesnapshot.FieldMarketHashName, pricesnapshot.FieldSource, pricesnapshot.FieldSourceLabel, pricesnapshot.FieldPageURL, pricesnapshot.FieldPriceText, pricesnapshot.FieldCurrency, pricesnapshot.FieldMetadata:
			values[i] = new(sql.NullString)
		case pricesnapshot.FieldFetchedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PriceSnapshot fields.
func (_m *PriceSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pricesnapshot.FieldMarketHashName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field market_hash_name", values[i])
			} else if value.Valid {
				_m.MarketHashName = value.String
			}
		case pricesnapshot.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case pricesnapshot.FieldSourceLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_label", values[i])
			} else if value.Valid {
				_m.SourceLabel = value.String
			}
		case pricesnapshot.FieldPageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field page_url", values[i])
			} else if value.Valid {
				_m.PageURL = value.String
			}
		case pricesnapshot.FieldPriceText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_text", values[i])
			} else if value.Valid {
				_m.PriceText = value.String
			}
		case pricesnapshot.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				_m.PriceCents = new(int64)
				*_m.PriceCents = value.Int64
			}
		case pricesnapshot.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case pricesnapshot.FieldFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fetched_at", values[i])
			} else if value.Valid {
				_m.FetchedAt = value.Time
			}
		case pricesnapshot.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PriceSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *PriceSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PriceSnapshot.
// Note that you need to call PriceSnapshot.Unwrap() before calling this method if this PriceSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PriceSnapshot) Update() *PriceSnapshotUpdateOne {
	return NewPriceSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PriceSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PriceSnapshot) Unwrap() *PriceSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PriceSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PriceSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("PriceSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("market_hash_name=")
	builder.WriteString(_m.MarketHashName)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_label=")
	builder.WriteString(_m.SourceLabel)
	builder.WriteString(", ")
	builder.WriteString("page_url=")
	builder.WriteString(_m.PageURL)
	builder.WriteString(", ")
	builder.WriteString("price_text=")
	builder.WriteString(_m.PriceText)
	builder.WriteString(", ")
	if v := _m.PriceCents; v != nil {
		builder.WriteString("price_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("fetched_at=")
	builder.WriteString(_m.FetchedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(_m.Metadata)
	builder.WriteByte(')')
	return builder.String()
}

// PriceSnapshots is a parsable slice of PriceSnapshot.
type PriceSnapshots []*PriceSnapshot
