// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/predicate"
	"SkinPrice/skinprice/internal/adapters/database/ent/skin"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SkinUpdate is the builder for updating Skin entities.
type SkinUpdate struct {
	config
	hooks    []Hook
	mutation *SkinMutation
}

// Where appends a list predicates to the SkinUpdate builder.
func (_u *SkinUpdate) Where(ps ...predicate.Skin) *SkinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMarketHashName sets the "market_hash_name" field.
func (_u *SkinUpdate) SetMarketHashName(v string) *SkinUpdate {
	_u.mutation.SetMarketHashName(v)
	return _u
}

// SetNillableMarketHashName sets the "market_hash_name" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableMarketHashName(v *string) *SkinUpdate {
	if v != nil {
		_u.SetMarketHashName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SkinUpdate) SetDisplayName(v string) *SkinUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableDisplayName(v *string) *SkinUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetNameColor sets the "name_color" field.
func (_u *SkinUpdate) SetNameColor(v string) *SkinUpdate {
	_u.mutation.SetNameColor(v)
	return _u
}

// SetNillableNameColor sets the "name_color" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableNameColor(v *string) *SkinUpdate {
	if v != nil {
		_u.SetNameColor(*v)
	}
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *SkinUpdate) SetIconURL(v string) *SkinUpdate {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableIconURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *SkinUpdate) SetPageURL(v string) *SkinUpdate {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillablePageURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// SetPriceText sets the "price_text" field.
func (_u *SkinUpdate) SetPriceText(v string) *SkinUpdate {
	_u.mutation.SetPriceText(v)
	return _u
}

// SetNillablePriceText sets the "price_text" field if the given value is not nil.
func (_u *SkinUpdate) SetNillablePriceText(v *string) *SkinUpdate {
	if v != nil {
		_u.SetPriceText(*v)
	}
	return _u
}

// SetSteamPageURL sets the "steam_page_url" field.
func (_u *SkinUpdate) SetSteamPageURL(v string) *SkinUpdate {
	_u.mutation.SetSteamPageURL(v)
	return _u
}

// SetNillableSteamPageURL sets the "steam_page_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableSteamPageURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetSteamPageURL(*v)
	}
	return _u
}

// SetSteamPriceText sets the "steam_price_text" field.
func (_u *SkinUpdate) SetSteamPriceText(v string) *SkinUpdate {
	_u.mutation.SetSteamPriceText(v)
	return _u
}

// SetNillableSteamPriceText sets the "steam_price_text" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableSteamPriceText(v *string) *SkinUpdate {
	if v != nil {
		_u.SetSteamPriceText(*v)
	}
	return _u
}

// SetSteamUpdatedAt sets the "steam_updated_at" field.
func (_u *SkinUpdate) SetSteamUpdatedAt(v time.Time) *SkinUpdate {
	_u.mutation.SetSteamUpdatedAt(v)
	return _u
}

// SetNillableSteamUpdatedAt sets the "steam_updated_at" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableSteamUpdatedAt(v *time.Time) *SkinUpdate {
	if v != nil {
		_u.SetSteamUpdatedAt(*v)
	}
	return _u
}

// ClearSteamUpdatedAt clears the value of the "steam_updated_at" field.
func (_u *SkinUpdate) ClearSteamUpdatedAt() *SkinUpdate {
	_u.mutation.ClearSteamUpdatedAt()
	return _u
}

// SetLisskinsPageURL sets the "lisskins_page_url" field.
func (_u *SkinUpdate) SetLisskinsPageURL(v string) *SkinUpdate {
	_u.mutation.SetLisskinsPageURL(v)
	return _u
}

// SetNillableLisskinsPageURL sets the "lisskins_page_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableLisskinsPageURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetLisskinsPageURL(*v)
	}
	return _u
}

// SetLisskinsPriceText sets the "lisskins_price_text" field.
func (_u *SkinUpdate) SetLisskinsPriceText(v string) *SkinUpdate {
	_u.mutation.SetLisskinsPriceText(v)
	return _u
}

// SetNillableLisskinsPriceText sets the "lisskins_price_text" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableLisskinsPriceText(v *string) *SkinUpdate {
	if v != nil {
		_u.SetLisskinsPriceText(*v)
	}
	return _u
}

// SetLisskinsUpdatedAt sets the "lisskins_updated_at" field.
func (_u *SkinUpdate) SetLisskinsUpdatedAt(v time.Time) *SkinUpdate {
	_u.mutation.SetLisskinsUpdatedAt(v)
	return _u
}

// SetNillableLisskinsUpdatedAt sets the "lisskins_updated_at" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableLisskinsUpdatedAt(v *time.Time) *SkinUpdate {
	if v != nil {
		_u.SetLisskinsUpdatedAt(*v)
	}
	return _u
}

// ClearLisskinsUpdatedAt clears the value of the "lisskins_updated_at" field.
func (_u *SkinUpdate) ClearLisskinsUpdatedAt() *SkinUpdate {
	_u.mutation.ClearLisskinsUpdatedAt()
	return _u
}

// SetCstmPageURL sets the "cstm_page_url" field.
func (_u *SkinUpdate) SetCstmPageURL(v string) *SkinUpdate {
	_u.mutation.SetCstmPageURL(v)
	return _u
}

// SetNillableCstmPageURL sets the "cstm_page_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableCstmPageURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetCstmPageURL(*v)
	}
	return _u
}

// SetCstmPriceText sets the "cstm_price_text" field.
func (_u *SkinUpdate) SetCstmPriceText(v string) *SkinUpdate {
	_u.mutation.SetCstmPriceText(v)
	return _u
}

// SetNillableCstmPriceText sets the "cstm_price_text" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableCstmPriceText(v *string) *SkinUpdate {
	if v != nil {
		_u.SetCstmPriceText(*v)
	}
	return _u
}

// SetCstmUpdatedAt sets the "cstm_updated_at" field.
func (_u *SkinUpdate) SetCstmUpdatedAt(v time.Time) *SkinUpdate {
	_u.mutation.SetCstmUpdatedAt(v)
	return _u
}

// SetNillableCstmUpdatedAt sets the "cstm_updated_at" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableCstmUpdatedAt(v *time.Time) *SkinUpdate {
	if v != nil {
		_u.SetCstmUpdatedAt(*v)
	}
	return _u
}

// ClearCstmUpdatedAt clears the value of the "cstm_updated_at" field.
func (_u *SkinUpdate) ClearCstmUpdatedAt() *SkinUpdate {
	_u.mutation.ClearCstmUpdatedAt()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SkinUpdate) SetCurrency(v string) *SkinUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableCurrency(v *string) *SkinUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkinUpdate) SetUpdatedAt(v time.Time) *SkinUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableUpdatedAt(v *time.Time) *SkinUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SkinUpdate) ClearUpdatedAt() *SkinUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the SkinMutation object of the builder.
func (_u *SkinUpdate) Mutation() *SkinMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkinUpdate) check() error {
	if v, ok := _u.mutation.MarketHashName(); ok {
		if err := skin.MarketHashNameValidator(v); err != nil {
			return &ValidationError{Name: "market_hash_name", err: fmt.Errorf(`ent: validator failed for field "Skin.market_hash_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := skin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Skin.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SkinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skin.Table, skin.Columns, sqlgraph.NewFieldSpec(skin.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MarketHashName(); ok {
		_spec.SetField(skin.FieldMarketHashName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(skin.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameColor(); ok {
		_spec.SetField(skin.FieldNameColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(skin.FieldIconURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(skin.FieldPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceText(); ok {
		_spec.SetField(skin.FieldPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SteamPageURL(); ok {
		_spec.SetField(skin.FieldSteamPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.SteamPriceText(); ok {
		_spec.SetField(skin.FieldSteamPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SteamUpdatedAt(); ok {
		_spec.SetField(skin.FieldSteamUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SteamUpdatedAtCleared() {
		_spec.ClearField(skin.FieldSteamUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LisskinsPageURL(); ok {
		_spec.SetField(skin.FieldLisskinsPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.LisskinsPriceText(); ok {
		_spec.SetField(skin.FieldLisskinsPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.LisskinsUpdatedAt(); ok {
		_spec.SetField(skin.FieldLisskinsUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LisskinsUpdatedAtCleared() {
		_spec.ClearField(skin.FieldLisskinsUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CstmPageURL(); ok {
		_spec.SetField(skin.FieldCstmPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CstmPriceText(); ok {
		_spec.SetField(skin.FieldCstmPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.CstmUpdatedAt(); ok {
		_spec.SetField(skin.FieldCstmUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CstmUpdatedAtCleared() {
		_spec.ClearField(skin.FieldCstmUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(skin.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(skin.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkinUpdateOne is the builder for updating a single Skin entity.
type SkinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkinMutation
}

// SetMarketHashName sets the "market_hash_name" field.
func (_u *SkinUpdateOne) SetMarketHashName(v string) *SkinUpdateOne {
	_u.mutation.SetMarketHashName(v)
	return _u
}

// SetNillableMarketHashName sets the "market_hash_name" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableMarketHashName(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetMarketHashName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SkinUpdateOne) SetDisplayName(v string) *SkinUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableDisplayName(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetNameColor sets the "name_color" field.
func (_u *SkinUpdateOne) SetNameColor(v string) *SkinUpdateOne {
	_u.mutation.SetNameColor(v)
	return _u
}

// SetNillableNameColor sets the "name_color" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableNameColor(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetNameColor(*v)
	}
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *SkinUpdateOne) SetIconURL(v string) *SkinUpdateOne {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableIconURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *SkinUpdateOne) SetPageURL(v string) *SkinUpdateOne {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillablePageURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// SetPriceText sets the "price_text" field.
func (_u *SkinUpdateOne) SetPriceText(v string) *SkinUpdateOne {
	_u.mutation.SetPriceText(v)
	return _u
}

// SetNillablePriceText sets the "price_text" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillablePriceText(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetPriceText(*v)
	}
	return _u
}

// SetSteamPageURL sets the "steam_page_url" field.
func (_u *SkinUpdateOne) SetSteamPageURL(v string) *SkinUpdateOne {
	_u.mutation.SetSteamPageURL(v)
	return _u
}

// SetNillableSteamPageURL sets the "steam_page_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableSteamPageURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetSteamPageURL(*v)
	}
	return _u
}

// SetSteamPriceText sets the "steam_price_text" field.
func (_u *SkinUpdateOne) SetSteamPriceText(v string) *SkinUpdateOne {
	_u.mutation.SetSteamPriceText(v)
	return _u
}

// SetNillableSteamPriceText sets the "steam_price_text" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableSteamPriceText(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetSteamPriceText(*v)
	}
	return _u
}

// SetSteamUpdatedAt sets the "steam_updated_at" field.
func (_u *SkinUpdateOne) SetSteamUpdatedAt(v time.Time) *SkinUpdateOne {
	_u.mutation.SetSteamUpdatedAt(v)
	return _u
}

// SetNillableSteamUpdatedAt sets the "steam_updated_at" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableSteamUpdatedAt(v *time.Time) *SkinUpdateOne {
	if v != nil {
		_u.SetSteamUpdatedAt(*v)
	}
	return _u
}

// ClearSteamUpdatedAt clears the value of the "steam_updated_at" field.
func (_u *SkinUpdateOne) ClearSteamUpdatedAt() *SkinUpdateOne {
	_u.mutation.ClearSteamUpdatedAt()
	return _u
}

// SetLisskinsPageURL sets the "lisskins_page_url" field.
func (_u *SkinUpdateOne) SetLisskinsPageURL(v string) *SkinUpdateOne {
	_u.mutation.SetLisskinsPageURL(v)
	return _u
}

// SetNillableLisskinsPageURL sets the "lisskins_page_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableLisskinsPageURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetLisskinsPageURL(*v)
	}
	return _u
}

// SetLisskinsPriceText sets the "lisskins_price_text" field.
func (_u *SkinUpdateOne) SetLisskinsPriceText(v string) *SkinUpdateOne {
	_u.mutation.SetLisskinsPriceText(v)
	return _u
}

// SetNillableLisskinsPriceText sets the "lisskins_price_text" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableLisskinsPriceText(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetLisskinsPriceText(*v)
	}
	return _u
}

// SetLisskinsUpdatedAt sets the "lisskins_updated_at" field.
func (_u *SkinUpdateOne) SetLisskinsUpdatedAt(v time.Time) *SkinUpdateOne {
	_u.mutation.SetLisskinsUpdatedAt(v)
	return _u
}

// SetNillableLisskinsUpdatedAt sets the "lisskins_updated_at" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableLisskinsUpdatedAt(v *time.Time) *SkinUpdateOne {
	if v != nil {
		_u.SetLisskinsUpdatedAt(*v)
	}
	return _u
}

// ClearLisskinsUpdatedAt clears the value of the "lisskins_updated_at" field.
func (_u *SkinUpdateOne) ClearLisskinsUpdatedAt() *SkinUpdateOne {
	_u.mutation.ClearLisskinsUpdatedAt()
	return _u
}

// SetCstmPageURL sets the "cstm_page_url" field.
func (_u *SkinUpdateOne) SetCstmPageURL(v string) *SkinUpdateOne {
	_u.mutation.SetCstmPageURL(v)
	return _u
}

// SetNillableCstmPageURL sets the "cstm_page_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableCstmPageURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetCstmPageURL(*v)
	}
	return _u
}

// SetCstmPriceText sets the "cstm_price_text" field.
func (_u *SkinUpdateOne) SetCstmPriceText(v string) *SkinUpdateOne {
	_u.mutation.SetCstmPriceText(v)
	return _u
}

// SetNillableCstmPriceText sets the "cstm_price_text" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableCstmPriceText(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetCstmPriceText(*v)
	}
	return _u
}

// SetCstmUpdatedAt sets the "cstm_updated_at" field.
func (_u *SkinUpdateOne) SetCstmUpdatedAt(v time.Time) *SkinUpdateOne {
	_u.mutation.SetCstmUpdatedAt(v)
	return _u
}

// SetNillableCstmUpdatedAt sets the "cstm_updated_at" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableCstmUpdatedAt(v *time.Time) *SkinUpdateOne {
	if v != nil {
		_u.SetCstmUpdatedAt(*v)
	}
	return _u
}

// ClearCstmUpdatedAt clears the value of the "cstm_updated_at" field.
func (_u *SkinUpdateOne) ClearCstmUpdatedAt() *SkinUpdateOne {
	_u.mutation.ClearCstmUpdatedAt()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SkinUpdateOne) SetCurrency(v string) *SkinUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableCurrency(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkinUpdateOne) SetUpdatedAt(v time.Time) *SkinUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableUpdatedAt(v *time.Time) *SkinUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SkinUpdateOne) ClearUpdatedAt() *SkinUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the SkinMutation object of the builder.
func (_u *SkinUpdateOne) Mutation() *SkinMutation {
	return _u.mutation
}

// Where appends a list predicates to the SkinUpdate builder.
func (_u *SkinUpdateOne) Where(ps ...predicate.Skin) *SkinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkinUpdateOne) Select(field string, fields ...string) *SkinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skin entity.
func (_u *SkinUpdateOne) Save(ctx context.Context) (*Skin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkinUpdateOne) SaveX(ctx context.Context) *Skin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkinUpdateOne) check() error {
	if v, ok := _u.mutation.MarketHashName(); ok {
		if err := skin.MarketHashNameValidator(v); err != nil {
			return &ValidationError{Name: "market_hash_name", err: fmt.Errorf(`ent: validator failed for field "Skin.market_hash_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := skin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Skin.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SkinUpdateOne) sqlSave(ctx context.Context) (_node *Skin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skin.Table, skin.Columns, sqlgraph.NewFieldSpec(skin.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skin.FieldID)
		for _, f := range fields {
			if !skin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MarketHashName(); ok {
		_spec.SetField(skin.FieldMarketHashName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(skin.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameColor(); ok {
		_spec.SetField(skin.FieldNameColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(skin.FieldIconURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(skin.FieldPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceText(); ok {
		_spec.SetField(skin.FieldPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SteamPageURL(); ok {
		_spec.SetField(skin.FieldSteamPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.SteamPriceText(); ok {
		_spec.SetField(skin.FieldSteamPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SteamUpdatedAt(); ok {
		_spec.SetField(skin.FieldSteamUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SteamUpdatedAtCleared() {
		_spec.ClearField(skin.FieldSteamUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LisskinsPageURL(); ok {
		_spec.SetField(skin.FieldLisskinsPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.LisskinsPriceText(); ok {
		_spec.SetField(skin.FieldLisskinsPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.LisskinsUpdatedAt(); ok {
		_spec.SetField(skin.FieldLisskinsUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LisskinsUpdatedAtCleared() {
		_spec.ClearField(skin.FieldLisskinsUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CstmPageURL(); ok {
		_spec.SetField(skin.FieldCstmPageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CstmPriceText(); ok {
		_spec.SetField(skin.FieldCstmPriceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.CstmUpdatedAt(); ok {
		_spec.SetField(skin.FieldCstmUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CstmUpdatedAtCleared() {
		_spec.ClearField(skin.FieldCstmUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(skin.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(skin.FieldUpdatedAt, field.TypeTime)
	}
	_node = &Skin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
