// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/skin"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Skin is the model entity for the Skin schema.
type Skin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MarketHashName holds the value of the "market_hash_name" field.
	MarketHashName string `json:"market_hash_name,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// IconURL holds the value of the "icon_url" field.
	IconURL string `json:"icon_url,omitempty"`
	// PageURL holds the value of the "page_url" field.
	PageURL      string `json:"page_url,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Skin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skin.FieldID:
			values[i] = new(sql.NullInt64)
		case skin.FieldMarketHashName, skin.FieldDisplayName, skin.FieldIconURL, skin.FieldPageURL:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Skin fields.
func (_m *Skin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case skin.FieldMarketHashName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field market_hash_name", values[i])
			} else if value.Valid {
				_m.MarketHashName = value.String
			}
		case skin.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case skin.FieldIconURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_url", values[i])
			} else if value.Valid {
				_m.IconURL = value.String
			}
		case skin.FieldPageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field page_url", values[i])
			} else if value.Valid {
				_m.PageURL = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Skin.
// This includes values selected through modifiers, order, etc.
func (_m *Skin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Skin.
// Note that you need to call Skin.Unwrap() before calling this method if this Skin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Skin) Update() *SkinUpdateOne {
	return NewSkinClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Skin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Skin) Unwrap() *Skin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Skin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Skin) String() string {
	var builder strings.Builder
	builder.WriteString("Skin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("market_hash_name=")
	builder.WriteString(_m.MarketHashName)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("icon_url=")
	builder.WriteString(_m.IconURL)
	builder.WriteString(", ")
	builder.WriteString("page_url=")
	builder.WriteString(_m.PageURL)
	builder.WriteByte(')')
	return builder.String()
}

// Skins is a parsable slice of Skin.
type Skins []*Skin
