// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/predicate"
	"SkinPrice/skinprice/internal/adapters/database/ent/skin"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SkinUpdate is the builder for updating Skin entities.
type SkinUpdate struct {
	config
	hooks    []Hook
	mutation *SkinMutation
}

// Where appends a list predicates to the SkinUpdate builder.
func (_u *SkinUpdate) Where(ps ...predicate.Skin) *SkinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMarketHashName sets the "market_hash_name" field.
func (_u *SkinUpdate) SetMarketHashName(v string) *SkinUpdate {
	_u.mutation.SetMarketHashName(v)
	return _u
}

// SetNillableMarketHashName sets the "market_hash_name" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableMarketHashName(v *string) *SkinUpdate {
	if v != nil {
		_u.SetMarketHashName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SkinUpdate) SetDisplayName(v string) *SkinUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableDisplayName(v *string) *SkinUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *SkinUpdate) SetIconURL(v string) *SkinUpdate {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillableIconURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// ClearIconURL clears the value of the "icon_url" field.
func (_u *SkinUpdate) ClearIconURL() *SkinUpdate {
	_u.mutation.ClearIconURL()
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *SkinUpdate) SetPageURL(v string) *SkinUpdate {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *SkinUpdate) SetNillablePageURL(v *string) *SkinUpdate {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// ClearPageURL clears the value of the "page_url" field.
func (_u *SkinUpdate) ClearPageURL() *SkinUpdate {
	_u.mutation.ClearPageURL()
	return _u
}

// Mutation returns the SkinMutation object of the builder.
func (_u *SkinUpdate) Mutation() *SkinMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkinUpdate) check() error {
	if v, ok := _u.mutation.MarketHashName(); ok {
		if err := skin.MarketHashNameValidator(v); err != nil {
			return &ValidationError{Name: "market_hash_name", err: fmt.Errorf(`ent: validator failed for field "Skin.market_hash_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := skin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Skin.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SkinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skin.Table, skin.Columns, sqlgraph.NewFieldSpec(skin.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MarketHashName(); ok {
		_spec.SetField(skin.FieldMarketHashName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(skin.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(skin.FieldIconURL, field.TypeString, value)
	}
	if _u.mutation.IconURLCleared() {
		_spec.ClearField(skin.FieldIconURL, field.TypeString)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(skin.FieldPageURL, field.TypeString, value)
	}
	if _u.mutation.PageURLCleared() {
		_spec.ClearField(skin.FieldPageURL, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkinUpdateOne is the builder for updating a single Skin entity.
type SkinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkinMutation
}

// SetMarketHashName sets the "market_hash_name" field.
func (_u *SkinUpdateOne) SetMarketHashName(v string) *SkinUpdateOne {
	_u.mutation.SetMarketHashName(v)
	return _u
}

// SetNillableMarketHashName sets the "market_hash_name" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableMarketHashName(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetMarketHashName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SkinUpdateOne) SetDisplayName(v string) *SkinUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableDisplayName(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *SkinUpdateOne) SetIconURL(v string) *SkinUpdateOne {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillableIconURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// ClearIconURL clears the value of the "icon_url" field.
func (_u *SkinUpdateOne) ClearIconURL() *SkinUpdateOne {
	_u.mutation.ClearIconURL()
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *SkinUpdateOne) SetPageURL(v string) *SkinUpdateOne {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *SkinUpdateOne) SetNillablePageURL(v *string) *SkinUpdateOne {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// ClearPageURL clears the value of the "page_url" field.
func (_u *SkinUpdateOne) ClearPageURL() *SkinUpdateOne {
	_u.mutation.ClearPageURL()
	return _u
}

// Mutation returns the SkinMutation object of the builder.
func (_u *SkinUpdateOne) Mutation() *SkinMutation {
	return _u.mutation
}

// Where appends a list predicates to the SkinUpdate builder.
func (_u *SkinUpdateOne) Where(ps ...predicate.Skin) *SkinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkinUpdateOne) Select(field string, fields ...string) *SkinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skin entity.
func (_u *SkinUpdateOne) Save(ctx context.Context) (*Skin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkinUpdateOne) SaveX(ctx context.Context) *Skin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkinUpdateOne) check() error {
	if v, ok := _u.mutation.MarketHashName(); ok {
		if err := skin.MarketHashNameValidator(v); err != nil {
			return &ValidationError{Name: "market_hash_name", err: fmt.Errorf(`ent: validator failed for field "Skin.market_hash_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := skin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Skin.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SkinUpdateOne) sqlSave(ctx context.Context) (_node *Skin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skin.Table, skin.Columns, sqlgraph.NewFieldSpec(skin.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skin.FieldID)
		for _, f := range fields {
			if !skin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MarketHashName(); ok {
		_spec.SetField(skin.FieldMarketHashName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(skin.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(skin.FieldIconURL, field.TypeString, value)
	}
	if _u.mutation.IconURLCleared() {
		_spec.ClearField(skin.FieldIconURL, field.TypeString)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(skin.FieldPageURL, field.TypeString, value)
	}
	if _u.mutation.PageURLCleared() {
		_spec.ClearField(skin.FieldPageURL, field.TypeString)
	}
	_node = &Skin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
