// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SkinPrice/skinprice/internal/adapters/database/ent/sourcestate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SourceStateCreate is the builder for creating a SourceState entity.
type SourceStateCreate struct {
	config
	mutation *SourceStateMutation
	hooks    []Hook
}

// SetSource sets the "source" field.
func (_c *SourceStateCreate) SetSource(v string) *SourceStateCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SourceStateCreate) SetNillableSource(v *string) *SourceStateCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetAPITokenEncrypted sets the "api_token_encrypted" field.
func (_c *SourceStateCreate) SetAPITokenEncrypted(v string) *SourceStateCreate {
	_c.mutation.SetAPITokenEncrypted(v)
	return _c
}

// SetNillableAPITokenEncrypted sets the "api_token_encrypted" field if the given value is not nil.
func (_c *SourceStateCreate) SetNillableAPITokenEncrypted(v *string) *SourceStateCreate {
	if v != nil {
		_c.SetAPITokenEncrypted(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SourceStateCreate) SetUpdatedAt(v time.Time) *SourceStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SourceStateCreate) SetNillableUpdatedAt(v *time.Time) *SourceStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SourceStateMutation object of the builder.
func (_c *SourceStateCreate) Mutation() *SourceStateMutation {
	return _c.mutation
}

// Save creates the SourceState in the database.
func (_c *SourceStateCreate) Save(ctx context.Context) (*SourceState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceStateCreate) SaveX(ctx context.Context) *SourceState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceStateCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := sourcestate.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.APITokenEncrypted(); !ok {
		v := sourcestate.DefaultAPITokenEncrypted
		_c.mutation.SetAPITokenEncrypted(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sourcestate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceStateCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SourceState.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := sourcestate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SourceState.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APITokenEncrypted(); !ok {
		return &ValidationError{Name: "api_token_encrypted", err: errors.New(`ent: missing required field "SourceState.api_token_encrypted"`)}
	}
	return nil
}

func (_c *SourceStateCreate) sqlSave(ctx context.Context) (*SourceState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceStateCreate) createSpec() (*SourceState, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sourcestate.Table, sqlgraph.NewFieldSpec(sourcestate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(sourcestate.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.APITokenEncrypted(); ok {
		_spec.SetField(sourcestate.FieldAPITokenEncrypted, field.TypeString, value)
		_node.APITokenEncrypted = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sourcestate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	return _node, _spec
}

// SourceStateCreateBulk is the builder for creating many SourceState entities in bulk.
type SourceStateCreateBulk struct {
	config
	err      error
	builders []*SourceStateCreate
}

// Save creates the SourceState entities in the database.
func (_c *SourceStateCreateBulk) Save(ctx context.Context) ([]*SourceState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SourceState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceStateCreateBulk) SaveX(ctx context.Context) []*SourceState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
