export const UI_TEXT = {
  ctaAddSkins: "Добавить скины",
  ctaToHome: "На главную",
  ctaToSettings: "Настройки",
  ctaRetry: "Повторить",
  updateOne: "Обновить цену",
  updateOnePending: "Обновляем цену...",
  updateAll: "Обновить цены",
  updateAllPending: "Обновляем цены...",
  saveSkin: "Добавить",
  saveSkinPending: "Сохраняем скин...",
  saveSkinDone: "В коллекции",
  saveSkinAlready: "Скин уже в списке.",
  deleteSkin: "Удалить",
  deleteSkinPending: "Удаляем...",
  errLoadSaved: "Не удалось загрузить сохранённые скины.",
  errLoadNew: "Не удалось загрузить новые скины.",
  errUpdateOne: "Не удалось обновить цену.",
  errUpdateAll: "Не удалось обновить цены.",
  errSave: "Не удалось сохранить скин.",
  errDelete: "Не удалось удалить скин.",
  loadingSaved: "Загрузка сохранённых скинов...",
  loadingNew: "Загрузка новых скинов...",
  notFoundSaved: "Нет сохранённых скинов.",
  notFoundSearch: "По запросу ничего не найдено.",
  emptySavedHint: "Добавьте первый скин и начните отслеживать цены локально.",
  pageNotFound: "Страница не найдена.",
  priceLabel: "Цена",
  steamPriceLabel: "Steam",
  lisSkinsPriceLabel: "LisSkins",
  listingsLabel: "Лотов",
  updatedLabel: "Обновлено",
  updateOnePendingCompact: "Обновляем...",
  successUpdatedAll: "Готово: цены обновлены для {count} скинов.",
  partialUpdatedAll: "Обновление завершено: {updated} успешно, {failed} с ошибкой.",
  warningPartialUpdated: "Частичный успех: цены обновлены, но не удалось синхронизировать список ({message}).",
  saveDoneShort: "Скин сохранён.",
  searchAction: "Найти скин",
  searchPlaceholder: "Название скина (минимум 3 сим.)",
  loadMore: "Показать ещё",
  listFullyLoaded: "Список загружен полностью.",
  loadingMore: "Загружаем ещё...",
  openLink: "Открыть",
  collectionEyebrow: "Коллекция",
  searchEyebrow: "Поиск",
  settingsEyebrow: "Настройки",
  savedSkinsTitle: "Сохранённые скины",
  newSkinsTitle: "Добавление скинов",
  settingsTitle: "Параметры приложения",
  sourceSteamShort: "Steam",
  sourceLisSkinsShort: "LisSkins",
  notUpdatedYet: "ещё не обновлялось",
  lisSkinsTokenTitle: "Доступ к LisSkins",
  lisSkinsTokenRequired: "Для поиска в LisSkins сначала сохраните API-токен.",
  lisSkinsTokenHelp: "Сгенерируйте токен в личном кабинете LisSkins и используйте секции ниже для проверки и сохранения.",
  lisSkinsTokenConfigured: "Токен LisSkins уже сохранён на этом устройстве.",
  lisSkinsTokenLink: "Открыть страницу генерации токена",
  lisSkinsTokenLabel: "API-токен LisSkins",
  lisSkinsTokenPlaceholder: "Введите токен LisSkins",
  lisSkinsTokenSectionAccess: "1. Доступ к LisSkins",
  lisSkinsTokenSectionInput: "2. API-токен",
  lisSkinsTokenSectionLink: "3. Генерация токена",
  lisSkinsTokenShow: "Показать",
  lisSkinsTokenHide: "Скрыть",
  lisSkinsTokenCheck: "Проверить",
  lisSkinsTokenChecking: "Проверяем...",
  lisSkinsTokenStatusMissing: "Токен не указан",
  lisSkinsTokenStatusSaved: "Токен сохранён",
  lisSkinsTokenStatusVerified: "Токен проверен",
  lisSkinsTokenStatusAuthError: "Ошибка авторизации",
  lisSkinsTokenSave: "Сохранить",
  lisSkinsTokenSaving: "Сохраняем токен...",
  lisSkinsTokenSaved: "Токен LisSkins сохранён.",
  lisSkinsTokenReset: "Сбросить токен",
  lisSkinsTokenResetting: "Сбрасываем токен...",
  lisSkinsTokenResetDone: "Токен LisSkins сброшен.",
  errLisSkinsTokenSave: "Не удалось сохранить токен LisSkins.",
  errLisSkinsTokenReset: "Не удалось сбросить токен LisSkins.",
  settingsAutoSaved: "Изменения валюты и интервала сохраняются сразу на этом устройстве.",
  settingsCurrencyTitle: "Валюта цен",
  settingsCurrencyHelp: "Эта валюта используется на главной странице и при массовом обновлении сохранённых цен.",
  settingsRefreshTitle: "Автообновление главной страницы",
  settingsRefreshHelp: "Интервал задаётся в секундах. Пока открыта главная страница, приложение обновляет сохранённые цены автоматически.",
  settingsRefreshLabel: "Интервал в секундах",
  settingsRefreshHint: "Минимум 5 секунд, значение по умолчанию 30.",
} as const;
