export const UI_TEXT = {
  ctaAddSkins: "Добавить скины",
  ctaToHome: "На главную",
  ctaRetry: "Повторить",
  updateOne: "Обновить цену",
  updateOnePending: "Обновляем цену...",
  updateAll: "Обновить цены",
  updateAllPending: "Обновляем цены...",
  saveSkin: "Сохранить скин",
  saveSkinPending: "Сохраняем скин...",
  saveSkinDone: "Скин сохранён",
  saveSkinAlready: "Скин уже в списке.",
  deleteSkin: "Удалить",
  deleteSkinPending: "Удаляем...",
  errLoadSaved: "Не удалось загрузить сохранённые скины.",
  errLoadNew: "Не удалось загрузить новые скины.",
  errUpdateOne: "Не удалось обновить цену.",
  errUpdateAll: "Не удалось обновить цены.",
  errSave: "Не удалось сохранить скин.",
  errDelete: "Не удалось удалить скин.",
  loadingSaved: "Загрузка сохранённых скинов...",
  loadingNew: "Загрузка новых скинов...",
  notFoundSaved: "Нет сохранённых скинов.",
  notFoundSearch: "По запросу ничего не найдено.",
  emptySavedHint: "Добавьте первый скин и начните отслеживать цены локально.",
  pageNotFound: "Страница не найдена.",
  priceLabel: "Цена",
  listingsLabel: "Лотов",
  updatedLabel: "Обновлено",
  updateOnePendingCompact: "Обновляем...",
  successUpdatedAll: "Готово: цены обновлены для {count} скинов.",
  partialUpdatedAll: "Обновление завершено: {updated} успешно, {failed} с ошибкой.",
  warningPartialUpdated: "Частичный успех: цены обновлены, но не удалось синхронизировать список ({message}).",
  saveDoneShort: "Скин сохранён.",
  searchAction: "Найти скин",
  searchPlaceholder: "Введите название скина",
  searchHelper: "Поиск выполняется по Steam Market.",
  loadMore: "Загрузить ещё",
  listFullyLoaded: "Список загружен полностью.",
  loadingMore: "Загружаем ещё...",
  openLink: "Открыть",
  collectionEyebrow: "Коллекция",
  searchEyebrow: "Поиск",
  savedSkinsTitle: "Сохранённые скины",
  newSkinsTitle: "Добавление скинов",
  sourceTabsAriaLabel: "Источник поиска",
  sourceSteam: "Steam",
  sourceLisSkins: "LisSkins",
  lisSkinsTokenRequired: "Для поиска в LisSkins сначала сохраните API-токен.",
  lisSkinsTokenHelp: "Сгенерируйте токен в личном кабинете LisSkins и вставьте его сюда.",
  lisSkinsTokenLink: "Открыть страницу генерации токена",
  lisSkinsTokenPlaceholder: "Введите токен LisSkins",
  lisSkinsTokenSave: "Сохранить токен",
  lisSkinsTokenSaving: "Сохраняем токен...",
  lisSkinsTokenSaved: "Токен LisSkins сохранён. Повторяем поиск...",
  errLisSkinsTokenSave: "Не удалось сохранить токен LisSkins.",
} as const;
