// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSavedSkins(arg1: GetSavedSkinsFilter): Promise<SavedSkinsResponse>;
export function SearchNewSkins(arg1: SearchNewSkinsFilter): Promise<NewSkinsResponse>;
export function Shutdown(): Promise<void>;
export function UpdateAllSavedSkinsPrices(arg1: UpdateAllSavedSkinsPricesRequest): Promise<void>;
export function UpdateSavedSkinPrice(arg1: UpdateSavedSkinPriceRequest): Promise<void>;

export interface GetSavedSkinsFilter {
  limit: number;
  offset: number;
}

export interface SearchNewSkinsFilter {
  market_hash_name?: string;
  limit: number;
  offset: number;
}

export interface UpdateAllSavedSkinsPricesRequest {
  currency: string;
}

export interface UpdateSavedSkinPriceRequest {
  market_hash_name: string;
  currency: string;
}

export interface SavedSkinItem {
  market_hash_name: string;
  display_name: string;
  icon_url: string;
  page_url: string;
  price_text: string;
  currency: string;
}

export interface SavedSkinsResponse {
  items: SavedSkinItem[];
  total_count: number;
  limit: number;
  offset: number;
}

export interface NewSkinItem {
  market_hash_name: string;
  display_name: string;
  sell_listings: number;
  price_cents?: number;
  price_text: string;
  icon_url: string;
  page_url: string;
}

export interface NewSkinsResponse {
  items: NewSkinItem[];
  total_count: number;
  limit: number;
  offset: number;
}
