// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLisSkinsToken(): Promise<void>;
export function GetAppSettings(): Promise<AppSettingsResponse>;
export function GetSavedSkins(arg1: GetSavedSkinsFilter): Promise<SavedSkinsResponse>;
export function HasLisSkinsToken(): Promise<LisSkinsTokenStatusResponse>;
export function LogClientEvent(arg1: ClientLogEvent): Promise<void>;
export function SaveAppSettings(arg1: SaveAppSettingsRequest): Promise<void>;
export function SearchNewSkins(arg1: SearchNewSkinsFilter): Promise<NewSkinsResponse>;
export function SetLisSkinsToken(arg1: SetLisSkinsTokenRequest): Promise<void>;
export function Shutdown(): Promise<void>;
export function UpdateAllSavedSkinsPrices(arg1: UpdateAllSavedSkinsPricesRequest): Promise<UpdateAllSavedSkinsPricesResponse>;
export function UpdateSavedSkinPrice(arg1: UpdateSavedSkinPriceRequest): Promise<UpdateSavedSkinPriceResponse>;

export interface GetSavedSkinsFilter {
  limit: number;
  offset: number;
}

export interface AppSettingsResponse {
  currency: string;
  auto_refresh_interval_seconds: number;
  saved_skins_view_mode: string;
}

export interface SearchNewSkinsFilter {
  market_hash_name?: string;
  sort_column: string;
  sort_dir: string;
  price_min?: string;
  price_max?: string;
  search_descriptions: boolean;
  type: string[];
  weapon: string[];
  rarity: string[];
  exterior: string[];
  item_set: string[];
  pro_player: string[];
  sticker_capsule: string[];
  tournament_team: string[];
  limit: number;
  offset: number;
  cursor: string;
}

export interface UpdateAllSavedSkinsPricesRequest {
  currency: string;
}

export interface UpdateSavedSkinPriceRequest {
  market_hash_name: string;
  currency: string;
}

export interface SavedSkinItem {
  market_hash_name: string;
  display_name: string;
  icon_url: string;
  steam_page_url: string;
  steam_price_text: string;
  steam_updated_at: string;
  lisskins_page_url: string;
  lisskins_price_text: string;
  lisskins_updated_at: string;
  currency: string;
}

export interface SavedSkinsResponse {
  items: SavedSkinItem[];
  total_count: number;
  limit: number;
  offset: number;
}

export interface NewSkinItem {
  market_hash_name: string;
  display_name: string;
  sell_listings: number;
  price_cents?: number;
  price_text: string;
  icon_url: string;
  page_url: string;
}

export interface NewSkinsResponse {
  items: NewSkinItem[];
  total_count: number;
  limit: number;
  offset: number;
  next_cursor: string;
}

export interface UpdateSavedSkinPriceResponse {
  market_hash_name: string;
  steam_page_url: string;
  steam_price_text: string;
  steam_updated_at: string;
  lisskins_page_url: string;
  lisskins_price_text: string;
  lisskins_updated_at: string;
  currency: string;
}

export interface UpdateSavedSkinPriceFailure {
  market_hash_name: string;
  message: string;
}

export interface UpdateAllSavedSkinsPricesResponse {
  updated_count: number;
  failed_count: number;
  failures: UpdateSavedSkinPriceFailure[];
}

export interface ClientLogEvent {
  level: string;
  message: string;
  component: string;
  context: Record<string, unknown>;
}

export interface SetLisSkinsTokenRequest {
  token: string;
}

export interface SaveAppSettingsRequest {
  currency: string;
  auto_refresh_interval_seconds: number;
  saved_skins_view_mode: string;
}

export interface LisSkinsTokenStatusResponse {
  hasToken: boolean;
}
