// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppSetting is the predicate function for appsetting builders.
type AppSetting func(*sql.Selector)

// PriceSnapshot is the predicate function for pricesnapshot builders.
type PriceSnapshot func(*sql.Selector)

// Skin is the predicate function for skin builders.
type Skin func(*sql.Selector)

// SourceState is the predicate function for sourcestate builders.
type SourceState func(*sql.Selector)

// WatchlistItem is the predicate function for watchlistitem builders.
type WatchlistItem func(*sql.Selector)
